name = "podcast-sync"
main = "dist/index.js"
compatibility_date = "2025-05-02"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "podcast-sync"
database_id = "local"

[[durable_objects.bindings]]
name = "PROGRESS_DO"
class_name = "ProgressDO"

[[migrations]]
tag = "v1"
new_classes = ["ProgressDO"]

[assets]
directory = "src/assets"