// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Account struct {
	ID               string
	RssUrl           string
	OrderDir         string
	CurrentEpisodeID string
	PositionSec      float64
}
