// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id) VALUES (?) RETURNING id, rss_url, order_dir, current_episode_id, position_sec
`

func (q *Queries) CreateAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.RssUrl,
		&i.OrderDir,
		&i.CurrentEpisodeID,
		&i.PositionSec,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = ?
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAccount, id)
	return err
}

const getAccount = `-- name: GetAccount :one
SELECT id, rss_url, order_dir, current_episode_id, position_sec FROM accounts WHERE id = ?
`

func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.RssUrl,
		&i.OrderDir,
		&i.CurrentEpisodeID,
		&i.PositionSec,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET rss_url = ?,
    order_dir = ?,
    current_episode_id = ?,
    position_sec = ?
WHERE id = ?
RETURNING id, rss_url, order_dir, current_episode_id, position_sec
`

type UpdateAccountParams struct {
	RssUrl           string
	OrderDir         string
	CurrentEpisodeID string
	PositionSec      float64
	ID               string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.RssUrl,
		arg.OrderDir,
		arg.CurrentEpisodeID,
		arg.PositionSec,
		arg.ID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.RssUrl,
		&i.OrderDir,
		&i.CurrentEpisodeID,
		&i.PositionSec,
	)
	return i, err
}

const updatePosition = `-- name: UpdatePosition :exec
UPDATE accounts SET position_sec = ? WHERE id = ?
`

type UpdatePositionParams struct {
	PositionSec float64
	ID          string
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) error {
	_, err := q.db.ExecContext(ctx, updatePosition, arg.PositionSec, arg.ID)
	return err
}
